DATA:
  BATCH_SIZE: 128
  DATA_PATH: '../datasets'
  PATCH_SIZE: 17
  TEST_SIZE: 0.9
  TRAIN_SIZE: 0.9
  SAMPLE_MODE: 'random'
MODEL:
  TYPE: 'v1'
  EMBED_DIMENSION: 64
  DROP_PATH_RATE: 0.1
  GROUP_NORM: True
  DEPTHS: [2, 4, 2]
  SPA_QUERY_LEN: 7
  HEAD_TYPE: "AP"
TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 15




  