DATA:
  BATCH_SIZE: 16
  DATA_PATH: 'datasets'
  PATCH_SIZE: 17
  TEST_SIZE: 0.9
  TRAIN_SIZE: 0.9
  SAMPLE_MODE: 'random'
MODEL:
  TYPE: 'v1'
  EMBED_DIMENSION: 64
  DROP_PATH_RATE: 0.1
  GROUP_NORM: True
  DEPTHS: [1,2,1]
  HIDDEN_LEN: [256,64,16]
  SPE_HEAD_DIM: [64,16,4]
  SPA_QUERY_LEN: 5
  HEAD_TYPE: "AP"
  NUM_CLASSES: 17
TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 15




  